name: build
on: 
  push:
    paths:
      - '.github/workflows/build.yml'
      - 'packages/{core,fetcher,sdk}/src/**'
      - 'packages/{core,fetcher,sdk}/package.json'
      - 'test/**'
      - 'test/package.json'
  pull_request:
    paths:
      - '.github/workflows/build.yml'
      - 'packages/*/src/**'
      - 'packages/*/package.json'
      - 'test/**'
      - 'test/package.json'

jobs:
  Ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      - name: test
        working-directory: ./test
        run: npm start